<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Stack Management</name>
   <tag></tag>
   <elementGuidId>2d4227d5-18d9-4a61-8bcf-7090a272854d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='i6f8b8dd1-2fa9-11ef-8750-01b0c5971df6']/div/div/ul/li[6]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5b840ff3-ab1f-4133-97fc-ffd4d48b711a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>euiListGroupItem__button css-1dv0cqm-euiListGroupItem__inner-s-subdued-isClickable</value>
      <webElementGuid>3e9ea820-bb30-4f8a-8033-428e422b94f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://10.8.60.18:5601/app/management</value>
      <webElementGuid>6ae698b5-73aa-4a40-b98a-a76ae45177a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noreferrer</value>
      <webElementGuid>fa92ac76-9c17-4b06-a5a5-d32c12f876ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-subj</name>
      <type>Main</type>
      <value>collapsibleNavAppLink</value>
      <webElementGuid>6a51a0d2-d75d-49f9-be8f-d3a0a95eade3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Stack Management</value>
      <webElementGuid>480c332c-8b50-4368-8d75-9ecb755de366</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;i6f8b8dd1-2fa9-11ef-8750-01b0c5971df6&quot;)/div[@class=&quot;euiAccordion__children css-ip8p5q-euiAccordion__children&quot;]/div[@class=&quot;euiCollapsibleNavGroup__children css-r5f6vl-euiCollapsibleNavGroup__children-withHeading&quot;]/ul[@class=&quot;euiListGroup css-7bfi2k-euiListGroup-none&quot;]/li[@class=&quot;euiListGroupItem css-141g2ay-euiListGroupItem-subdued-s&quot;]/a[@class=&quot;euiListGroupItem__button css-1dv0cqm-euiListGroupItem__inner-s-subdued-isClickable&quot;]</value>
      <webElementGuid>8c48c452-4683-4531-a71c-03185fbf69f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='i6f8b8dd1-2fa9-11ef-8750-01b0c5971df6']/div/div/ul/li[6]/a</value>
      <webElementGuid>642f70bd-e0f4-4458-8644-53eee44cbb5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stack Monitoring'])[1]/following::a[1]</value>
      <webElementGuid>f54b2dbd-1c06-4ffb-b00f-2ef2f6dde660</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Osquery'])[1]/following::a[2]</value>
      <webElementGuid>6369b8de-8652-41c7-a493-423a59fa6af8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add integrations'])[2]/preceding::a[1]</value>
      <webElementGuid>74d9224e-6d93-4963-9535-f3e2a4a3193d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://10.8.60.18:5601/app/management')])[2]</value>
      <webElementGuid>6166b414-011e-496b-97a6-0ddc77f51da1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/div/ul/li[6]/a</value>
      <webElementGuid>a30e8c20-b13c-4a28-9573-05edf38b99f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://10.8.60.18:5601/app/management' and (text() = 'Stack Management' or . = 'Stack Management')]</value>
      <webElementGuid>c3bd3155-837b-405a-8b7e-e3068e00c1e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
