<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg__euiIcon css-1h0bwsh-euiIcon-m-isLoaded</name>
   <tag></tag>
   <elementGuidId>4236e8b5-7acb-4d47-8a45-91a465085135</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='^/'])[1]/following::*[name()='svg'][4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.euiHeaderSectionItem.header__toggleNavButtonSection.css-s1qjj2-euiHeaderSectionItem > button.euiButtonEmpty.euiHeaderSectionItemButton.css-1al3gsh-euiButtonDisplay-euiButtonEmpty-m-empty-text-euiHeaderSectionItemButton > span.euiButtonEmpty__content.css-1bascr2-euiButtonDisplayContent > span.eui-textTruncate.euiButtonEmpty__text > span.euiHeaderSectionItemButton__content.css-1f67s81-euiHeaderSectionItemButton__content > svg.euiIcon.css-1h0bwsh-euiIcon-m-isLoaded</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>c6b48c62-899a-41ac-b96c-f17aed1cc847</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>24290f8e-9f1a-47f6-8698-5f8723771c3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>9afb4f84-3b96-4edb-9397-5f8234678066</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>6199489b-0c6f-491a-8c75-1f390c244a3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>2b3dc686-98f2-4946-81e1-315d9910b102</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 16 16</value>
      <webElementGuid>4ab87f46-297e-4529-9362-024b8e025cfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>euiIcon css-1h0bwsh-euiIcon-m-isLoaded</value>
      <webElementGuid>a180a053-b559-4fad-82eb-391d132214fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>63d6765c-d1ab-4827-98a5-0cf453ac341b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-icon-type</name>
      <type>Main</type>
      <value>menu</value>
      <webElementGuid>1ee43a68-a191-4627-955e-b2e84109d4a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-is-loaded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>38bda469-8400-40c1-aa30-b75b33c61d96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2c403b10-b1ac-45c4-b494-0154be736a15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;globalHeaderBars&quot;)/div[@class=&quot;euiHeader header__secondBar css-6v6lyj-euiHeader-fixed-default&quot;]/div[@class=&quot;euiHeaderSection css-pnqsdi-euiHeaderSection&quot;]/div[@class=&quot;euiHeaderSectionItem header__toggleNavButtonSection css-s1qjj2-euiHeaderSectionItem&quot;]/button[@class=&quot;euiButtonEmpty euiHeaderSectionItemButton css-1al3gsh-euiButtonDisplay-euiButtonEmpty-m-empty-text-euiHeaderSectionItemButton&quot;]/span[@class=&quot;euiButtonEmpty__content css-1bascr2-euiButtonDisplayContent&quot;]/span[@class=&quot;eui-textTruncate euiButtonEmpty__text&quot;]/span[@class=&quot;euiHeaderSectionItemButton__content css-1f67s81-euiHeaderSectionItemButton__content&quot;]/svg[@class=&quot;euiIcon css-1h0bwsh-euiIcon-m-isLoaded&quot;]</value>
      <webElementGuid>d7844cc5-14c2-4843-9451-d5e9d6be9eb3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='^/'])[1]/following::*[name()='svg'][4]</value>
      <webElementGuid>a1211cb2-2838-4c54-8115-46865f22b9f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skip to main content'])[1]/following::*[name()='svg'][7]</value>
      <webElementGuid>e529ed00-3530-4109-aa27-a25129f941d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>dc4bd855-0d61-418c-b9b8-629b99787567</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome home'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>08f78c40-75a0-43da-8758-2c907eafadc5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
