<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Password_euiButtonIcon euiFormContro_b47ff5</name>
   <tag></tag>
   <elementGuidId>86a663df-b574-4f74-a373-d34e2dc8444d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.euiButtonIcon.euiFormControlLayout__append.css-9sj1hz-euiButtonIcon-xs-empty-primary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>94206e31-7b3e-4015-852b-32a387388d97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>euiButtonIcon euiFormControlLayout__append css-9sj1hz-euiButtonIcon-xs-empty-primary</value>
      <webElementGuid>ab319379-4e25-43e6-80d3-19334e51acc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d8fd0777-f437-49ea-b1d5-c69a4be91022</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Show password as plain text. Note: this will visually expose your password on the screen.</value>
      <webElementGuid>e9871b98-2a6c-4fc8-8d8e-f7447d95fae3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Show password as plain text. Note: this will visually expose your password on the screen.</value>
      <webElementGuid>48e7e5ce-05b5-47fa-b132-7fb5964ddd12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ib27f4901-32cf-11ef-9020-77ec877f0a1b-row&quot;)/div[@class=&quot;euiFormRow__fieldWrapper&quot;]/div[@class=&quot;euiFormControlLayout euiFormControlLayout--group&quot;]/button[@class=&quot;euiButtonIcon euiFormControlLayout__append css-9sj1hz-euiButtonIcon-xs-empty-primary&quot;]</value>
      <webElementGuid>c57e4f1e-a4a0-4c94-b022-7f4fcc753ba5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>de4d2353-e8fb-423b-8f71-75c9976db0d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ib27f4901-32cf-11ef-9020-77ec877f0a1b-row']/div[2]/div/button</value>
      <webElementGuid>66f94eff-8de9-43a2-9a84-0d60139c27f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::button[1]</value>
      <webElementGuid>0f376205-2616-443f-a2d1-274224be7180</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Username'])[1]/following::button[1]</value>
      <webElementGuid>94e68cba-e514-4541-a105-a764b7d17b1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log in'])[1]/preceding::button[1]</value>
      <webElementGuid>22cd3c55-af6d-4d5b-bfd2-9f1aefa62b1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>fcc52a56-d28c-418a-a539-678c3d92a515</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @title = 'Show password as plain text. Note: this will visually expose your password on the screen.']</value>
      <webElementGuid>3bd0fc4b-5e1f-4253-9917-147400dcdff7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
