<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_password</name>
   <tag></tag>
   <elementGuidId>c022c558-1602-4913-ba8d-2bc4ca7d4d8c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ifa8d7a91-32da-11ef-9f99-dd01abfbb16a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'password' and starts-with(@id, 'i') and @name = 'password']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ifa8d7a91-32da-11ef-9f99-dd01abfbb16a']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>437bd193-4348-4b9e-8f67-5da523dedf86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>6480d470-a969-4130-8caa-52b619c99c5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>starts with</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>8d15e4b2-b06b-4df0-bb18-faaf16ec1e8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>990f9823-4bf7-4475-8324-d9fab7fb2b82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>euiFieldPassword euiFieldPassword--inGroup euiFieldPassword--withToggle</value>
      <webElementGuid>03dc336d-01d9-49a2-bc9d-4f7105fce6ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a7e3376e-00f7-4a3d-ae78-faa2b52bdfcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-subj</name>
      <type>Main</type>
      <value>loginPassword</value>
      <webElementGuid>f17beef9-c15a-473f-bff7-a0e6e92a96b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c5202a67-e378-484a-95a9-f35fdbc0b5e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ifa8d7a91-32da-11ef-9f99-dd01abfbb16a&quot;)</value>
      <webElementGuid>0a8f23ed-91ad-434e-a82f-554d4dc6b9cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ifa8d7a91-32da-11ef-9f99-dd01abfbb16a']</value>
      <webElementGuid>722c2554-f177-4ab7-9785-8a0604f0f9f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ifa8d7a91-32da-11ef-9f99-dd01abfbb16a-row']/div[2]/div/div/input</value>
      <webElementGuid>1dce0ca4-e9a3-449d-86e8-53c507d1a6af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/input</value>
      <webElementGuid>04925922-9c0c-4b66-b960-b8bbfafef0b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'ifa8d7a91-32da-11ef-9f99-dd01abfbb16a' and @name = 'password']</value>
      <webElementGuid>8f4fead0-c8f6-4a05-9bf7-e59c1a45f208</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
