<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Username_username</name>
   <tag></tag>
   <elementGuidId>9553b972-67ad-44de-bea0-4238f4b04662</elementGuidId>
   <imagePath>Screenshots/Targets/Page_Elastic/input_Username_username.png</imagePath>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#i1caa5901-32da-11ef-ac97-1131125dcff1</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value>Screenshots/Targets/Page_Elastic/input_Username_username.png</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and starts-with(@id, 'i') and @name = 'username']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='i1caa5901-32da-11ef-ac97-1131125dcff1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e3e0dcdf-0aa7-4368-8612-b0fe11f0d2b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>53ec3e2b-21da-4961-b4ef-555cbdc823e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>starts with</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>6989d5fc-591c-45be-bd6a-83f5d7f36580</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>aa0def1a-dfdc-442b-9777-ce9ed9559099</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>euiFieldText</value>
      <webElementGuid>4fafa598-e410-47ba-906c-5a13ebce42c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>7411ca9d-052e-4077-8924-77f2ca867fb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-subj</name>
      <type>Main</type>
      <value>loginUsername</value>
      <webElementGuid>2d22e21c-4d09-4b0c-b1ca-ad735e69f21d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8026d93f-fe75-4967-bd2a-b13b94789e6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>matches regex</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;i1caa5901-32da-11ef-ac97-1131125dcff1&quot;)</value>
      <webElementGuid>4c947e6c-753e-4f0c-9c18-b52e92ef8965</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='i1caa5901-32da-11ef-ac97-1131125dcff1']</value>
      <webElementGuid>3c3c3462-a2ba-469e-b343-546deaff3548</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='i1caa5901-32da-11ef-ac97-1131125dcff1-row']/div[2]/div/div/input</value>
      <webElementGuid>8e9f9c48-be77-430b-a538-b685fae74d09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>acf618f0-2596-4eaa-b47a-2fec6b6d80f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'i1caa5901-32da-11ef-ac97-1131125dcff1' and @name = 'username']</value>
      <webElementGuid>b33c1cd6-93c8-44a5-a5c6-e328b6e58027</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
