<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_Welcome to Elastic_euiIcon css-ep274o-e_1f7af9</name>
   <tag></tag>
   <elementGuidId>d72aaed5-d341-42ff-97d7-168c75c701f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome to Elastic'])[1]/preceding::*[name()='svg'][1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>svg.euiIcon.css-ep274o-euiIcon-xxl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>ce1532be-329e-4308-98d7-62b6d4cc5667</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>ad3935f8-8665-4d42-b9cf-b2684261b869</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>801fa26c-6d2d-4775-94b6-24f6ee38a9db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>5e4ab07e-30c5-4112-ab5a-741320fd6085</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>ca76c801-ea9a-4b9d-9189-639bc179aa43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>logoElastic</value>
      <webElementGuid>77284c77-ceea-40cc-9f56-895715164b49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 32 32</value>
      <webElementGuid>0816bcf8-da02-499e-a270-3f38f4e2e4c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>euiIcon css-ep274o-euiIcon-xxl</value>
      <webElementGuid>62bc4667-7746-490f-8520-b10c051c1030</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2ff1ec67-e869-45ae-9040-93c540786fbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8ebd9360-16b8-42af-a3a9-f44d666ea221</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kibana-body&quot;)/div[@class=&quot;kbnAppWrapper kbnAppWrapper--hiddenChrome&quot;]/div[@class=&quot;kbnAppWrapper&quot;]/div[@class=&quot;loginWelcome login-form&quot;]/header[@class=&quot;loginWelcome__header&quot;]/div[@class=&quot;loginWelcome__content eui-textCenter&quot;]/span[@class=&quot;loginWelcome__logo&quot;]/svg[@class=&quot;euiIcon css-ep274o-euiIcon-xxl&quot;]</value>
      <webElementGuid>348af02e-9b3e-4521-9286-300d057d53f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome to Elastic'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>31c8a5bd-0b18-48a1-8588-19bb8f668373</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Username'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>90cb0b7e-1ea3-465b-a80b-88be59647190</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
