<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Dashboards</name>
   <tag></tag>
   <elementGuidId>1470c7ee-8ae9-41a7-abb0-e9c61e0277f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ic37d3741-2fa4-11ef-a437-b799d844546b']/div/div/ul/li[2]/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a08dcdb3-e6cd-433f-a5b2-f15ab9136980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>euiListGroupItem__label css-nlq75h-euiListGroupItem__label-truncate</value>
      <webElementGuid>456a6fef-1ecd-4c9a-bf46-e88f0ebe1937</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Dashboards</value>
      <webElementGuid>d829040f-0a3d-4b1c-9f8c-39becbcb550a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dashboards</value>
      <webElementGuid>d130514b-8f1b-4c83-b75b-87b9bc4c18ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ic37d3741-2fa4-11ef-a437-b799d844546b&quot;)/div[@class=&quot;euiAccordion__children css-ip8p5q-euiAccordion__children&quot;]/div[@class=&quot;euiCollapsibleNavGroup__children css-r5f6vl-euiCollapsibleNavGroup__children-withHeading&quot;]/ul[@class=&quot;euiListGroup css-7bfi2k-euiListGroup-none&quot;]/li[@class=&quot;euiListGroupItem css-141g2ay-euiListGroupItem-subdued-s&quot;]/a[@class=&quot;euiListGroupItem__button css-1dv0cqm-euiListGroupItem__inner-s-subdued-isClickable&quot;]/span[@class=&quot;euiListGroupItem__label css-nlq75h-euiListGroupItem__label-truncate&quot;]</value>
      <webElementGuid>543e133e-84b7-4f04-93ca-62f16f01152a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ic37d3741-2fa4-11ef-a437-b799d844546b']/div/div/ul/li[2]/a/span</value>
      <webElementGuid>1318f0f0-04b5-47c9-ac20-b9c52af938ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Discover'])[1]/following::span[1]</value>
      <webElementGuid>32adc310-871c-449d-be11-389d3fd21992</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Analytics'])[1]/following::span[2]</value>
      <webElementGuid>dfb93c56-17a6-49a3-8bed-879b95e58024</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Canvas'])[1]/preceding::span[1]</value>
      <webElementGuid>0ba788e5-2a6a-4435-ae1d-607edcae1075</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Maps'])[1]/preceding::span[2]</value>
      <webElementGuid>e260d81d-5c6e-41d8-aa95-e2820e799d5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Dashboards']/parent::*</value>
      <webElementGuid>a6f88684-158d-4978-8412-17783b531dd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/span</value>
      <webElementGuid>db21187b-7011-457e-a414-4377db633b9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'Dashboards' and (text() = 'Dashboards' or . = 'Dashboards')]</value>
      <webElementGuid>78cf0ddf-9141-49b2-9881-cba21fab634e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
