<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button__euiButtonEmpty euiHeaderSectionItem_e7e826</name>
   <tag></tag>
   <elementGuidId>7c63c2d7-36c7-42ea-8fc0-566563fb4089</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.euiHeaderSectionItem.header__toggleNavButtonSection.css-s1qjj2-euiHeaderSectionItem > button.euiButtonEmpty.euiHeaderSectionItemButton.css-1al3gsh-euiButtonDisplay-euiButtonEmpty-m-empty-text-euiHeaderSectionItemButton</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>55cb5646-ce61-4e3d-8b90-4c1d8c340027</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>euiButtonEmpty euiHeaderSectionItemButton css-1al3gsh-euiButtonDisplay-euiButtonEmpty-m-empty-text-euiHeaderSectionItemButton</value>
      <webElementGuid>6a3ae1ea-71cf-4be1-8a1d-db112c6fecc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f9daf6da-c901-408f-a852-9820d4ecc7ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-pressed</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3a34b59c-023d-46a0-a6e7-fa5c2812c8b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-subj</name>
      <type>Main</type>
      <value>toggleNavButton</value>
      <webElementGuid>d32029e9-451d-451c-8439-ad3700109eb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Toggle primary navigation</value>
      <webElementGuid>6709442d-6cbf-4c63-8c83-65461902e55e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>57c8b2a4-7be4-4a61-8d88-ca7cce78d527</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>i92532801-2fa4-11ef-a437-b799d844546b</value>
      <webElementGuid>617a2c40-c740-46f8-958a-9b74aa4b44b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;globalHeaderBars&quot;)/div[@class=&quot;euiHeader header__secondBar css-6v6lyj-euiHeader-fixed-default&quot;]/div[@class=&quot;euiHeaderSection css-pnqsdi-euiHeaderSection&quot;]/div[@class=&quot;euiHeaderSectionItem header__toggleNavButtonSection css-s1qjj2-euiHeaderSectionItem&quot;]/button[@class=&quot;euiButtonEmpty euiHeaderSectionItemButton css-1al3gsh-euiButtonDisplay-euiButtonEmpty-m-empty-text-euiHeaderSectionItemButton&quot;]</value>
      <webElementGuid>4baf49ed-6344-44cf-9865-eb87294df713</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[5]</value>
      <webElementGuid>e7ef069d-57ce-4a8b-a81d-23a9bd5c761b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='globalHeaderBars']/div[2]/div/div/button</value>
      <webElementGuid>9c047eb0-6fc5-4a60-afc8-b68a1f775198</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='^/'])[1]/following::button[4]</value>
      <webElementGuid>7455c8fc-ccfe-46bf-801a-16e9e0beb619</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skip to main content'])[1]/following::button[4]</value>
      <webElementGuid>14cf5a83-5c34-4bd0-9ad5-87f9af71a080</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clusters'])[1]/preceding::button[2]</value>
      <webElementGuid>3b052d7b-c55c-4891-a5fe-f158f917cafc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alerts and rules'])[1]/preceding::button[2]</value>
      <webElementGuid>5fa00465-0228-4212-97bd-6b7ddaee9ce8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/button</value>
      <webElementGuid>e60117ea-bcbf-41f6-989e-20757d41ef82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button']</value>
      <webElementGuid>c9d08911-6f43-4c78-9c29-eaa8c550af1c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
